[web]
web ansible_host=localhost ansible_port=2201

[db]
db ansible_host=localhost ansible_port=2202

[monitoring]
monitoring ansible_host=localhost ansible_port=2203

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible_lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
